name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Expo Doctor
        run: npx expo-doctor

      - name: Prebuild iOS
        run: npx expo prebuild --platform ios --clean

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Build App
        run: |
          cd ios
          xcodebuild \
            -workspace Wise.xcworkspace \
            -scheme Wise \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Create IPA
        run: |
          mkdir Payload
          APP=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          cp -R "$APP" Payload
          zip -r Wise.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Wise-IPA
          path: Wise.ipa